# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('video_url', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
